language: node_js
node_js:
  - '4'
  - 'iojs-3'
  - 'iojs-2'
  - '0.12'
before_script:
- sleep 10
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
services:
  - elasticsearch
